services:
  api:
    container_name: api
    build: .
    command: sh -c "npx prisma migrate deploy && npm start"
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - ACCESS_TOKEN_SECRET=after_all_this_time
      - REFRESH_TOKEN_SECRET=always
      - ACCESS_TOKEN_EXPIRATION_IN_SECONDS=600 # 10 min
      - REFRESH_TOKEN_EXPIRATION_IN_SECONDS=3600 # 1 hour
      - DATABASE_URL=postgresql://rick:morty@db:5432/authentication_api
      - REDIS_URL=redis://redis:6379
    networks:
      - private
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:3000/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
  db:
    container_name: db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=rick
      - POSTGRES_PASSWORD=morty
      - POSTGRES_DB=authentication_api
    networks:
      - private
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'rick', '-d', 'authentication_api']
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - private
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
networks:
  private: {}
volumes:
  db_data: {}
